FROM maven:3.8.6-openjdk-18 as builder
WORKDIR /usr/src/wasm-central-mediator
COPY ./mediator .
RUN mvn -f /usr/src/wasm-central-mediator/pom.xml clean package

FROM debian:buster-slim
RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/wasm-central-mediator/
COPY --from=builder /usr/src/wasm-central/target/release/wasm-central-cli /usr/local/bin/wasm-central-cli
COPY ./rt.sh .
ENTRYPOINT ["rt.sh"]