[package]
name = "wasm-central-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
quickjs-wasm-rs = { git = "https://github.com/Shopify/javy", features = ["json"] }
wee_alloc = "0.4.5"
once_cell = "1.4.0"
